### ISSUE TITLE
Correctifs préavis mise à la retraite CC 176

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/code-du-travail-numerique#5668]
### Outil préavis de retraite -> mise à la retraite

Il s'agit du préavis en cas de **mise à la retraite**

**1) Supprimer la note (2) du résultat :** 

![image](https://github.com/SocialGouv/code-du-travail-numerique/assets/84397271/91a02c8d-17a4-4787-9f08-df84432aa468)

**2) Remplacer l’article 32.2 par l’article 38 dans tous les cas :** https://www.legifrance.gouv.fr/conv_coll/id/KALIARTI000039117114/?idConteneur=KALICONT000005635184

**Comment by maxgfr** [comment]
Pour info : Il y a une autre notification que j'ai laissé qui est celle ci :

```yml
contrat salarié . convention collective . industrie pharmaceutique . notification:
  applicable si:
    toutes ces conditions:
      - conclu après 1 juillet 2019
      - groupe >= 4
      - contrat salarié . préavis de retraite = contrat salarié . préavis de retraite collective
  type: notification
  description: Cette durée ne s'applique que si les salariés ne bénéficient pas des dispositions de l'article 4 de la convention collective nationale de retraite et de prévoyance des cadres du 14/3/1947.
  valeur: oui
```
