### ISSUE TITLE
[Fiche MT] Erreur de récupération des tableaux

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/code-du-travail-numerique#6256]
https://code-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr/fiche-ministere-travail/les-sanctions-liees-au-travail-illegal

![Image](https://github.com/user-attachments/assets/18f33981-d097-4bd3-9dfa-4616d85dcb0d)

**Comment by m-maillot** [comment]
Le tableau est dispo en scrollant verticalement.

**Comment by m-maillot** [comment]
Ils ajoutent ce css dans leur styles pour que le tableau soit ok :

```css
.fr-table__content table,.fr-table__content table * {
    white-space: normal;
}
```
